"""baseline schema

Revision ID: f8e55b9c78f2
Revises: 
Create Date: 2026-09-03 13:31:28.006099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e55b9c78f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('monthly_income', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('existing_emi', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pan')
    )
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_call_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('state', sa.Enum('STARTED', 'PROSPECT', 'LEAD_CAPTURED', 'IDENTITY_MATCHED', 'IDENTITY_VERIFIED', 'ELIGIBILITY_ASSESSED', 'CONSENT_RECORDED', 'COMPLETED', 'ESCALATED', 'BLOCKED', name='sessionstate'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('identity_attempts', sa.Integer(), nullable=False),
    sa.Column('otp_resends', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_sessions_external_call_id'), ['external_call_id'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('disclosure_version', sa.String(length=20), nullable=False),
    sa.Column('verbatim_response', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_session_id'), ['session_id'], unique=False)

    op.create_table('eligibility_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=40), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REFERRED', 'DECLINED', name='eligibilitydecision'), nullable=False),
    sa.Column('approved_amount', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('monthly_instalment', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_assessments_session_id'), ['session_id'], unique=False)

    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_ref', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('queue', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_ref')
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalations_session_id'), ['session_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('product_interest', sa.String(length=40), nullable=False),
    sa.Column('stated_monthly_income', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_pan'), ['pan'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_session_id'), ['session_id'], unique=False)

    op.create_table('otp_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('code_salt', sa.String(length=32), nullable=False),
    sa.Column('code_digest', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenges_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_session_id'), ['session_id'], unique=False)

    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=60), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('request_digest', sa.JSON(), nullable=False),
    sa.Column('response_digest', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'idempotency_key', name='uq_tool_idempotency')
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_session_id'), ['session_id'], unique=False)

    op.create_table('application_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_links_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_links_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_links_token_digest'), ['token_digest'], unique=True)

    op.create_table('application_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=False),
    sa.Column('address_line', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('credit_check_consent', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_submissions_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_submissions_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_submissions_session_id'))
        batch_op.drop_index(batch_op.f('ix_application_submissions_lead_id'))

    op.drop_table('application_submissions')
    with op.batch_alter_table('application_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_links_token_digest'))
        batch_op.drop_index(batch_op.f('ix_application_links_session_id'))
        batch_op.drop_index(batch_op.f('ix_application_links_lead_id'))

    op.drop_table('application_links')
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_session_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenges_session_id'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_customer_id'))

    op.drop_table('otp_challenges')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_session_id'))
        batch_op.drop_index(batch_op.f('ix_leads_pan'))

    op.drop_table('leads')
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalations_session_id'))

    op.drop_table('escalations')
    with op.batch_alter_table('eligibility_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_assessments_session_id'))

    op.drop_table('eligibility_assessments')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_session_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('onboarding_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_sessions_external_call_id'))

    op.drop_table('onboarding_sessions')
    op.drop_table('customers')
    # ### end Alembic commands ###
